### PR TITLE
Diary Fixes

### LINKED ISSUE #2132: Karamja Diary bug
image

Fire Cape required for easy diary

### PR DESCRIPTION
**Pull request by 6enny6**
- Removed fire cape requirement from Karamja easy diary (lol)
- Changed Kourend Elite wc req from 95 to 90
- Added a --diary bank flag (shows diary items + lamps)

closes #2132

### CODE REVIEW

File: src/lib/data/filterables.ts [hunk 1]
```diff
@@ -803,6 +858,11 @@ export const filterableTypes: Filterable[] = [
 		aliases: ['diango', 'daily', 'dailies'],
 		items: diango
 	},
+	{
+		name: 'Diaries',
+		aliases: ['diaries', 'diary', 'ad'],
+		items: diaries
+	},
```
Comment (gc) [inline src/lib/data/filterables.ts:865]: test it!

Comment (Lilylicious) [reply src/lib/data/filterables.ts:865]: image

Comment (gc) [reply src/lib/data/filterables.ts:865]: I totally misread what this was for, i thought i was looking at these being added to the CL.
