### PR TITLE
gilded skilling item

### LINKED ISSUE #4859: Gilded axe gives no skilling boost
## 🐛 Bug Report

Gilded axe gives no speed boost while doing woodcutting. Lower tier axes (steel, iron) give a speed boost while having gilded axe equipped and/or in the bank. gilded should give the same boost as rune axe.
975D08A1-A945-4F42-8DEA-52CA2E8C2EE4

### PR DESCRIPTION
**Pull request by Souzer**
gives gilded tools the same speed boosts as rune tools

closes #4859

### Other checks:

-   [x] I have tested all my changes thoroughly.

### CODE REVIEW

File: src/lib/data/similarItems.ts [hunk 1]
```diff
@@ -56,6 +56,8 @@ const bowfaCorruptSimilar = resolveItems([
 ]);
 
 const source: [string, (string | number)[]][] = [
+	['Rune Axe', ['Gilded Axe']],
+	['Rune Pickaxe', ['Gilded Pickaxe']],
```
Comment (gc) [inline src/lib/data/similarItems.ts:60]: these arent following the capitalization standard, `Rune axe`

**Review by gc — CHANGES_REQUESTED** [review]

**Comment by gc** [comment]
Actually I don't think this is even the right way to do it. Just go to the place where their boost is defined, and change the gilded axe/whatever to match the rune one.
